<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php echo $this->form()->openTag($form) ?>
        <legend>Recuperar Clave</legend>
        <!--<h4>Por favor completa el siguiente formulario.</h4>-->
        <div class="row">
            <?php $element = $form->get('email'); ?>
            <div  class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">

                <div class="col-xs-12 col-md-12">

                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <?php
                        echo $this->formElementErrors()
                                ->setMessageOpenFormat('<span class="help-block">')
                                ->setMessageSeparatorString('</span><span class="help-block">')
                                ->setMessageCloseString('</span>')
                                ->render($element);
                        ?>

                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-12 radio">
                <?php echo $this->formElement($form->get('submit')); ?>
            </div>
        </div>       
        <?php echo $this->form()->closeTag($form); ?>

    </div>

</div>
