<legend> <?php echo $this->element->getOption('label'); ?> </legend>
<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">
    <div class="col-xs-12 col-md-12 col-lg-12">

        <?php echo $this->formElement($this->element); ?>
        <?php if ($this->formElementErrors($this->element)) : ?>
            <?php
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<span class="help-block">')
                    ->setMessageSeparatorString('</span><span class="help-block">')
                    ->setMessageCloseString('</span>')
                    ->render($element);
            ?>

        <?php endif; ?>
    </div>
</div>
