<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">
    <div class="col-sm-offset-2 col-sm-10">

        <div class="checkbox">
            <label>
                <?php echo $this->formElement($this->element); ?> <?php echo $this->element->getOption('label'); ?>
            </label>

            <?php if ($this->formElementErrors($this->element)) : ?>
                <?php
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<span class="help-block">')
                        ->setMessageSeparatorString('</span><span class="help-block">')
                        ->setMessageCloseString('</span>')
                        ->render($element);
                ?>

            <?php endif; ?>
        </div>
    </div>
</div>
