<?php
/**
 * Created by IntelliJ IDEA.
 * User: afurgeri
 * Date: 05/04/19
 * Time: 17:27
 */

namespace ZfMetal\Security\Services;


use Doctrine\ORM\EntityManager;
use Zend\Authentication\Adapter;
use Zend\Authentication\Storage;
use ZfMetal\Security\Entity\Role;
use ZfMetal\Security\Entity\User;

class AuthenticationService extends \Zend\Authentication\AuthenticationService
{

    private $em;

    public function __construct(Storage\StorageInterface $storage = null, Adapter\AdapterInterface $adapter = null, EntityManager $entityManager)
    {
        parent::__construct($storage, $adapter);
        $this->em = $entityManager;
    }

    public function getIdentity()
    {
        /**
         * @var User $identity
         */
        $identity =  parent::getIdentity(); // TODO: Change the autogenerated stub

        if ($identity){
            $identity = $this->getEm()->getRepository(User::class)->find($identity->getId());
        }

        return $identity;
    }

    /**
     * @return EntityManager
     */
    public function getEm()
    {
        return $this->em;
    }

}