<div class="row">
    <div class="col-lg-2 col-md-4 col-xs-6 col-lg-offset-3">
        <a href="/admin/users">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <i class="glyphicon glyphicon-user cubeIcon"></i>
                </div>
                <div class="panel-body text-center">Gestion de Usuarios</div>
            </div>
        </a>
    </div>
    <div class="col-lg-2 col-md-4 col-xs-6">
        <a href="/admin/roles">
            <div class="panel panel-success">

                <div class="panel-heading">
                    <i class="glyphicon glyphicon-cog cubeIcon"></i>
                </div>
                <div class="panel-body text-center">Gestion de Roles</div>
            </div>
        </a>
    </div>
    <div class="col-lg-2 col-md-4 col-xs-6">
        <a href="/admin/groups">
            <div class="panel panel-warning">

                <div class="panel-heading">
                    <i class="glyphicon glyphicon-th cubeIcon"></i>

                </div>
                <div class="panel-body text-center">Gestion de Grupos</div>
            </div>
        </a>
    </div>
</div>

<style>
    .cubeIcon {
        position: relative;
        text-align: center;
        width: 100%;
        font-size: 80px;
        margin-top: 15px;
        margin-bottom: 10px;
    }
</style>