<a class="btn btn-default" href="/admin/roles">Admin Roles</a>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php echo $this->form()->openTag($form) ?>
        <legend>Registro</legend>
        <!--<h4>Por favor completa el siguiente formulario.</h4>-->
        <div class="row">

            <div class="col-xs-12 col-md-12">
                <div class="form-group">
                    <?php $element = $form->get('name'); ?>
                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                </div>
            </div>
        </div>

        <legend>Children:</legend>
        <div class="row">

            <div class="col-xs-12 col-md-12 ">
                <div class="form-group multi-check">
                    <?php $element = $form->get('children'); ?>

                    <?php echo $this->formElement($element); ?>
                </div>
            </div>

        </div>
        <legend>Permisos:</legend>
        <div class="row">

            <div class="col-xs-12 col-md-12 ">
                <div class="form-group multi-check">
                    <?php $element = $form->get('permissions'); ?>

                    <?php echo $this->formElement($element); ?>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-12 col-md-12 radio">
                <?php echo $this->formElement($form->get('submit')); ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>

    </div>

</div>


<style>
    .multi-check label {
        padding: 10px ! important;
        margin: 5px ! important;
    }

</style>
