<a class="btn btn-default" href="/admin/roles">Admin Roles</a>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php
        $groups = [
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'Role',
                'title' => "Role",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['name']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'ChildrenRoles',
                'title' => "Children roles",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['children']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'Permissions',
                'title' => "Permissions",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['permissions']
            ],
        ];

        echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_ONE, $groups);
        ?>

    </div>

</div>

