<a class="btn btn-default" href="/admin/roles">Admin Roles</a>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
          <?php
        
        $verticalGroups = [
            'Role' =>['name'],
            'Children roles' =>['children'],
            'Permissions' =>['permissions'],
        ];
        
        echo $this->renderForm($this->form,\ZfMetal\Commons\Consts::STYLE_VERTICAL,\ZfMetal\Commons\Consts::COLUMNS_ONE,null,$verticalGroups);
        ?>

    </div>

</div>

