
<a class="btn btn-default" href="/user/profile">Profile</a>

<div class="clearfix"></div>

<div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">

        <?php echo $this->form()->openTag($form) ?>

        <legend>Cambio de Contraseña</legend>

        <div class="row">

            <div class="col-xs-12 col-md-6">
                <div class="form-group">
                    <?php $element = $form->get('password'); ?>
                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                </div>
            </div>

            <div class="col-xs-12 col-md-6">
                <div class="form-group">
                    <?php $element = $form->get('password_verify'); ?>
                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-xs-12 col-md-12 radio">
                <?php echo $this->formElement($form->get('submit')); ?>
            </div>
        </div>

        <?php if ($form->getMessages()): ?>
            <?php foreach ($form->getMessages() as $msjs): ?>
                <?php foreach ($msjs as $key => $msj): ?>
                    <div class="alert alert-danger"><?php echo $msj; ?></div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php echo $this->form()->closeTag($form); ?>

    </div>


</div>
