<style>
    .navbar-profile-avatar{
        width:20px;
        height: 20px;
    }
</style>
    <?php if ($user = $this->isAuthenticated()): ?>


        <li class="dropdown">
            <a class="dropdown-toggle whitoutIcon" data-toggle="dropdown" href="#">

                <!--Picture OR Icon-->
                <?php if ($user->getImg()): ?>
                    <img src="<?php echo $this->getSecurityOptions()->getProfilePicturePathRelative(). $user->getImg(); ?>" class="img-circle  navbar-profile-avatar" alt="">
                <?php else: ?>
                    <i class="glyphicon glyphicon-user"></i>
                <?php endif; ?>
                
                <!--Name, Username or Email-->    
                <span class="navbar-profile-label ">
                    <?php if ($user->getName()): ?>
                        <?php echo $user->getName(); ?>
                    <?php elseif ($user->getUsername()): ?>
                        <?php echo $user->getUsername(); ?>
                    <?php else: ?>
                        <?php echo $user->getEmail(); ?>
                    <?php endif; ?>
                </span>
                
                <i class="glyphicon glyphicon-triangle-bottom"></i>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/user/profile"><i class="glyphicon glyphicon-th-list"></i> <?php echo $this->translate('Perfil'); ?></a>
                </li>    
           

                <li class="divider"></li>
                <li><a href="/user/logout"><i class="glyphicon glyphicon-log-out"></i>  <?php echo $this->translate('Cerrar Sesión'); ?></a>
                </li>
            </ul>
        </li>

        <?php if ($this->isGranted("admin-menu:view")): ?>
            <li class="dropdown ">
                <a class="dropdown-toggle whitoutIcon" data-toggle="dropdown" href="#">
                    <i class="glyphicon glyphicon-th-large"></i> <i class="glyphicon glyphicon-triangle-bottom"></i>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/admin/users"><i class="glyphicon glyphicon-user"></i> <?php echo $this->translate('Usuarios'); ?></a>
                    </li>    
                    <li class="divider"></li>
                    <li><a href="/admin/roles"><i class="glyphicon glyphicon-folder-close"></i>  <?php echo $this->translate('Roles'); ?></a>
                    </li>
                     <li class="divider"></li>
                    <li><a href="/admin/groups"><i class="glyphicon glyphicon-tower"></i>  <?php echo $this->translate('Grupos'); ?></a>
                    </li>

                </ul>
            </li>
        <?php endif; ?>

    <?php else: ?>
        <li class="pull-right">
            <a href="/user/login"><i><?php echo $this->translate('Iniciar Sesión'); ?> </i> <i class="glyphicon glyphicon-log-in"> </i></a>
        </li>

    <?php endif; ?>


