<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php echo $this->form()->openTag($form) ?>
        <legend>Registro</legend>
        <!--<h4>Por favor completa el siguiente formulario.</h4>-->
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <?php $element = $form->get('name'); ?>
                <label> <?php echo $element->getOption('label'); ?> </label>
                <?php echo $this->formElement($element); ?>
            </div>
            <div class="col-sm-12 col-md-6">
                <?php $element = $form->get('email'); ?>
                <label> <?php echo $element->getOption('label'); ?> </label>
                <?php echo $this->formElement($element); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <?php $element = $form->get('username'); ?>
                <label> <?php echo $element->getOption('label'); ?> </label>
                <?php echo $this->formElement($element); ?>
            </div>
            <div class="col-sm-12 col-md-6">
                <?php $element = $form->get('password'); ?>
                <label> <?php echo $element->getOption('label'); ?> </label>
                <?php echo $this->formElement($element); ?>
            </div>

            <div class="col-xs-12 col-md-12 radio">
                <?php echo $this->formElement($form->get('submit')); ?>
            </div>
        </div>       
        <?php echo $this->form()->closeTag($form); ?>

    </div>

</div>
