<?php echo $this->form()->openTag($form) ?>

<div class="form-group <?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">

    <?php $element = $form->get('_username'); ?>
    <label> <?php echo $element->getOption('label'); ?> </label>
    <?php echo $this->formElement($element); ?>

    <?php if ($element->getOption('description')): ?>
                   <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
               <?php endif; ?>
<?php if ($this->formElementErrors($this->element)) : ?>
        <?php
        
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<span class="help-block">')
                ->setMessageSeparatorString('</span><span class="help-block">')
                ->setMessageCloseString('</span>')
                ->render($element);
        ?>

               <?php endif; ?>


</div>

<div class="form-group <?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">
<?php $element = $form->get('_password'); ?>
    <label> <?php echo $element->getOption('label'); ?> </label>
    <?php
    echo $this->formElement($element);
    ?>
</div>

    <?php echo $this->formElement($form->get('submit')); ?>

<?php echo $this->form()->closeTag($form); ?>

