<a class="btn btn-default" href="/admin/users">Admin Users</a>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
       <?php
       $groups = [
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'User',
                'title' => "User",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['name', 'username', 'email', 'password','phone']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                'id' => 'enableUser',
                'title' => 'Enable/Disable User',
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['active']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                'id' => 'Roles',
                'title' => 'Roles',
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['roles']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                'id' => 'Groups',
                'title' => 'Groups',
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['groups']
            ],
        ];

        echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_TWO, $groups);
        ?>
    </div>

</div>


<style>
    .multi-check label{
        padding: 10px ! important;
        margin: 5px ! important;
    }

</style>
