<a class="btn btn-default" href="/admin/users">Admin Users</a>
<div class="clearfix"></div>

<div class="row">

    <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
        <table class="table table-striped table-right">
            <tr>
                <th class="text-right">Id:</th><td class="text-left"><?php echo $this->user->getId(); ?></td>
            </tr>

            <tr>
                <th class="text-right">Nombre:</th><td class="text-left"><?php echo $this->user->getName(); ?></td>
            </tr>

            <tr>
                <th class="text-right">Usuario:</th><td class="text-left"><?php echo $this->user->getUsername(); ?></td>
            </tr>

            <tr>
                <th class="text-right">Email:</th><td class="text-left"><?php echo $this->user->getEmail(); ?></td>
            </tr>
            
            <tr>
                <th class="text-right">Active:</th><td class="text-left"><?php echo $this->user->getActive(); ?></td>
            </tr>

            <tr>
                <th class="text-right">Roles:</th>
                <td class="text-left"> 
                    <ul>
                        <?php foreach ($this->user->getRoles() as $role): ?>
                            <li><?php echo $role->getName(); ?></li>

                        <?php endforeach; ?>
                    </ul>
                </td>
            </tr>
            
             <tr>
                <th class="text-right">Groups:</th>
                <td class="text-left"> 
                    <ul>
                        <?php foreach ($this->user->getGroups() as $group): ?>
                            <li><?php echo $group->getName(); ?></li>

                        <?php endforeach; ?>
                    </ul>
                </td>
            </tr>

        </table>
    </div>
    <div class="col-lg-4">

    </div>


</div>


