<?php
$this->notyFlash(true);
?>

<div class="row">
    <div class="col-xs-12 col-md-12">

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-4 text-center">
                        <img src="<?= $this->basePath('img/profile/') . $user->getImg(); ?>" alt=""
                             class="center-block img-circle img-responsive">
                        <br>
                        <!--                        <div>-->
                        <!--                            <a  class="btn btn-info btn-block"><span class="fa fa-gear"></span>-->
                        <!--                                Update User data-->
                        <!--                            </a>-->
                        <!--                        </div>-->

<!--                        <form action="<?= $this->url('zf-metal.user/profile/update-img') ?>" method="post" enctype="multipart/form-data">
                            <div class="btn btn-info btn-block">
                                <input type="file" accept="image/png, image/jpeg, image/gif"/>
                            </div>
                            <input class="btn btn-success btn-block" type="submit" value="Upload Image" name="submit">
                        </form>-->

                        <?php echo $this->form()->openTag($formImg) ?>

                        <div class="btn-block">
                            <?php echo $this->formElement($formImg->get('img')); ?>
         
                        </div>
                        <div class="btn-block">
                            <?php echo $this->formElement($formImg->get('submitbtn')); ?>
                        </div>


                        <?php echo $this->form()->closeTag($formImg); ?>

                        <br>

                        <div>
                            <a href="<?= $this->url('zf-metal.user/profile/password-update'); ?>" class="btn btn-warning btn-block"><span class="fa fa-gear"></span>
                                Change Password
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-8">
                        <h2><?= $user->getName(); ?></h2>
                        <p><strong>Email: </strong> <?= $user->getEmail(); ?> </p>

                        <p><strong>Roles: </strong>
                            <?php foreach ($user->getRoles() as $rol) : ?>
                                <span class="label label-info tags"><?= $rol->getName(); ?></span>
                            <?php endforeach; ?>
                        </p>

                        <p><strong>Permissions: </strong>
                            <?php foreach ($user->getRoles() as $rol) : ?>
                                <?php foreach ($rol->getPermissions() as $permission) : ?>

                                    <span class="label label-info tags"><?= $rol->getName() . ' - ' . $permission->getName(); ?></span>

                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </p>
                    </div>

                </div>
            </div>
        </div>


    </div>
</div>
