<a class="btn btn-default" href="/user/profile">Profile</a>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">

        <?php echo $this->form()->openTag($formManual) ?>
        <legend>Change Password</legend>
        <div class="row">
            <div class="col-xs-12 col-md-6">
                <div class="form-group">
                    <?php $element = $formManual->get('password'); ?>
                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                </div>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="form-group">
                    <?php $element = $formManual->get('password_verify'); ?>
                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-12 radio">
                <?php echo $this->formElement($formManual->get('submit')); ?>
            </div>
        </div>

        <?php if ($formManual->getMessages()): ?>
            <?php foreach ($formManual->getMessages() as $msjs): ?>
                <?php foreach ($msjs as $key => $msj): ?>
                    <div class="alert alert-danger"><?php echo $msj; ?></div>

                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php echo $this->form()->closeTag($formManual); ?>

    </div>


</div>
